name: '64bit Brainf**k winstaller'
on: [workflow_dispatch]

jobs:
  build_tauri_64bit:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Cache 64bit Windows cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-64bit-${{ hashFiles('**/src-tauri/Cargo.lock') }}
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            .yarn/
            node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@3.5.1 --activate
      - name: Install Rust
        run: rustup install nightly && rustup default nightly
      - name: Install Tauri CLI with Cargo
        run: cargo install tauri-cli
      - name: Install dependencies with Yarn
        run: yarn install
      - name: Compile Tauri
        run: cargo tauri build --target x86_64-pc-windows-msvc -- -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
      - name: Compress artifact with UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: src-tauri/target/x86_64-pc-windows-msvc/release/bfc-winstaller.exe
          args: -f9
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bfc-winstaller
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bfc-winstaller.exe